  GNU nano 8.3                                           nginx.conf                                                     server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    # Proxy para o backend (nome do serviço no docker-compose)
    location /chamados/ {
        proxy_pass http://backend:8080/chamados/;
    }

    location /usuarios/ {
        proxy_pass http://backend:8080/usuarios/;
    }

    location /auth/ {
        proxy_pass http://backend:8080/auth/;
    }

    # Angular SPA fallback
    try_files $uri $uri/ /index.html;